version: '3'

services:
  openldap:
    restart: "unless-stopped"
    image: bitnami/openldap:latest
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
    ports:
      - 1389:1389/tcp

